---

# superset defaults
superset_enabled: yes
superset_ssl_enabled: no
superset_db_name: "superset"
superset_project_dir: "{{ base_dir }}/superset"
superset_virtualenv_dir: "{{ base_dir }}/.virtualenvs/superset"
superset_username: admin
superset_firstname: Admin
superset_lastname: User
superset_email: superset-admin@example.com
superset_password: "{{ vault_default_superset_password }}"
superset_feature_flags: []

virtualenv_python_version: python3.14  # Used by Superset. TODO: DRY

superset_environment:
  SQLALCHEMY_DATABASE_URI: 'postgresql://{{ default_db_user }}:{{ default_db_password }}@{{ default_db_host }}:{{ default_db_port }}/{{ superset_db_name }}'
  FLASK_APP: superset
  SUPERSET_CONFIG_PATH: '{{ superset_project_dir }}/superset_config.py'
  SECRET_KEY: '{{ vault_superset_secret_key }}'
