---
# this task just installs certbot, but you still have to manually run it.
# also after it is run the nginx task will uninstall it.

- name: Add certbot apt repo
  apt_repository:
    repo: ppa:certbot/certbot
    update_cache: "{{ apt_update_cache }}"
    state: present
  register: add_cert_repo
  when: ssl_enabled or superset_ssl_enabled
  tags: letsencrypt



- name: Install Certbot
  apt:
    name:
      - software-properties-common
      - certbot
      - python3-certbot-nginx
  ignore_errors: '{{ ansible_check_mode }}'
  when: ssl_enabled or superset_ssl_enabled
  tags: letsencrypt

...
