---
- name: Configure logrotate for CommCare Data Pipeline logs
  community.general.logrotate:
    name: commcare-sync
    path: "{{ log_dir }}/*.log"
    options:
      - weekly
      - size 50M
      - rotate 8
      - missingok
      - compress
      - delaycompress
      - copytruncate
      - notifempty
  tags:
    - provision
    - logging
