---
- name: Configure logrotate for CommCare Data Pipeline logs
  community.general.logrotate:
    name: commcare-sync
    paths:
      - "{{ log_dir }}/*.log"
    rotation_period: weekly
    size: 50M
    rotate_count: 8
    missing_ok: true
    compress: true
    delay_compress: true
    copy_truncate: true
    not_if_empty: true
  tags:
    - provision
    - logging
