---
- name: Test
  ansible.builtin.command: echo it works!
  changed_when: false
  tags:
    - always

# Swap

- name: Include swap file tasks
  ansible.builtin.include_tasks: create_swap_file.yml
  when: swap_file_enabled
  tags:
    - provision
    - swap


# Packages

- name: Install security updates.
  ansible.builtin.apt:
    default_release: "{{ ansible_facts['distribution_release'] }}-security"
    update_cache: "{{ apt_update_cache }}"
    upgrade: dist
  tags:
    - provision
    - packages
    - packages.security
    - skip_ansible_lint
  when: env != 'dev'

- name: Install base packages.
  ansible.builtin.apt:
    name:
      - locales
      - build-essential
      - acl
      - ntp
      - htop
      - git
      - vim
      - screen
      - curl
      - "{{ base_python_package }}-pip"
      - "i{{ base_python_package }}"
      - libpq-dev
    update_cache: "{{ apt_update_cache }}"
    state: present
  tags:
    - provision
    - packages
    - skip_ansible_lint


# Python

- name: Include python tasks
  ansible.builtin.include_tasks: python.yml
  tags:
    - provision
    - python


# Users & Groups

- name: Create the app group.
  ansible.builtin.group:
    name: "{{ app_group }}"
    system: true
    state: present
  tags:
    - provision
    - users

- name: Create the app user.
  ansible.builtin.user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    shell: /bin/bash
    state: present
  tags:
    - provision
    - users

- name: Create application base directory.
  ansible.builtin.file:
    path: "{{ base_dir }}"
    group: "{{ app_group }}"
    mode: "0755"
    state: directory
  tags:
    - provision
    - users

- name: Create user .bash_aliases file.
  ansible.builtin.template:
    src: system/bash_aliases_script.sh.j2
    dest: "{{ home_dir }}/.bash_aliases"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0740"
    backup: true
  tags:
    - deploy
    - users


# logging

- name: Include logrotate tasks
  ansible.builtin.include_tasks: logrotate.yml
  tags:
    - provision
    - logging
