---
# Issue: https://github.com/ansible/ansible/issues/57529#issuecomment-513143430
- name: Gather facts
  hosts: all

- name: Create CommCare Data Pipeline server.
  hosts: all
  become: true
  become_user: root

  gather_facts: false

  roles:
    - postgres
    - redis
    - nginx
    - role: superset
      when: superset_enabled
    - django
    - commcare_sync
