---

ansible_python_interpreter: /usr/bin/python3
base_python_package: "python3"

apt_update_cache: true

swap_file_enabled: false
swap_file: /swapfile
swap_file_size_kb: 512

ssl_enabled: false

superset_secret_key: "{{ vault_superset_secret_key }}"

certbot_auto_renew: true

certbot_script: /opt/certbot-auto
certbot_dir: /etc/letsencrypt
certbot_admin_email: admin@example.com
certbot_domains:
  - example.com
  - www.example.com
