---

app_name: commcare_sync
app_user: "{{ app_name }}"
home_dir: /home/{{ app_user }}
app_group: webapps
project_name: commcare-sync
base_dir: "{{home_dir}}/www"
project_dir: "{{ base_dir }}/{{ project_name }}"
src_dir: "{{ base_dir }}/{{ project_name }}/code_root"
virtualenv_dir: "{{ src_dir }}/.venv"
run_dir: "{{ base_dir }}/run"
log_dir: "{{ base_dir }}/log"
static_dir: "{{ src_dir }}/static_root"
media_dir: "{{ src_dir }}/media"

commcare_sync_export_periodicity: 43200  # 60 * 60 * 12 = every 12 hours
project_timezone: 'America/New_York'
commcare_default_server: 'https://www.commcarehq.org'

django_settings_module: "{{ app_name }}.settings"
django_secret_key: "{{ vault_django_secret_key }}"
django_fernet_keys: "{{ vault_django_fernet_keys }}"
django_allow_public_signups: no
django_migrate: true
django_collectstatic: true

sentry_dsn: "{{ vault_sentry_dsn }}"
mapbox_api_key: "{{ vault_mapbox_api_key }}"

app_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"

gunicorn_num_workers: 3
gunicorn_max_requests: 0
gunicorn_reload_workers: true
gunicorn_timeout_seconds: 30

nginx_access_log_file: "{{ log_dir }}/nginx.access.log"
nginx_error_log_file: "{{ log_dir }}/nginx.error.log"
