---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:24.04
    pre_build_image: true
provisioner:
  name: ansible
  env:
    # workaround for molecule-docker 2.1.0 broken conditional with ansible-core 2.20+
    # https://github.com/ansible-community/molecule-plugins/issues/294
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "true"
    ANSIBLE_ROLES_PATH: "../../../../roles"
  inventory:
    group_vars:
      all:
        apt_update_cache: true
        app_name: commcare_sync
        app_user: commcare_sync
        app_group: webapps
        project_name: commcare-sync
        ssl_enabled: false
        env: test
        home_dir: /home/commcare_sync
        base_dir: /home/commcare_sync/www
        src_dir: /home/commcare_sync/www/commcare-sync/code_root
        run_dir: /home/commcare_sync/www/run
        log_dir: /home/commcare_sync/www/log
        static_dir: /home/commcare_sync/www/commcare-sync/code_root/static_root
        media_dir: /home/commcare_sync/www/commcare-sync/code_root/media
        nginx_access_log_file: /home/commcare_sync/www/log/nginx.access.log
        nginx_error_log_file: /home/commcare_sync/www/log/nginx.error.log
        gunicorn_timeout_seconds: 30
        public_host: localhost
verifier:
  name: ansible
