---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install sudo
      ansible.builtin.raw: apt-get update && apt-get install -y sudo python3

- name: Create prerequisites
  hosts: all
  become: true
  tasks:
    - name: Create app group
      ansible.builtin.group:
        name: "{{ app_group }}"
        state: present

    - name: Create log directory
      ansible.builtin.file:
        path: "{{ log_dir }}"
        state: directory
        mode: "0755"
