---

# Database

- name: Ensure the superset database is created.
  become: yes
  become_user: "{{ postgresql_user }}"
  community.postgresql.postgresql_db:
    name: "{{ superset_db_name }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template1'
    state: present
  tags:
    - provision
    - superset

- name: Ensure the default user has access to the database.
  become: yes
  become_user: "{{ postgresql_user }}"
  community.postgresql.postgresql_user:
    db: "{{ superset_db_name }}"
    name: "{{ default_db_user }}"
    password: "{{ default_db_password }}"
    encrypted: yes
    priv: ALL
    state: present
  tags:
    - provision
    - superset


# Virtualenv

- name: Create the superset virtualenv.
  ansible.builtin.command: virtualenv -p {{ virtualenv_python_version }} {{ superset_virtualenv_dir }}
  args:
    creates: "{{ superset_virtualenv_dir }}/bin/activate"
  tags:
    - deploy
    - superset

- name: Change ownership of superset virtualenv.
  ansible.builtin.file:
    dest: "{{ superset_virtualenv_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: yes
  tags:
    - deploy
    - superset

- name: Create the virtualenv postactivate script to set environment variables.
  ansible.builtin.template:
    src: superset/superset_postactivate_script.sh.j2
    dest: "{{ superset_virtualenv_dir }}/bin/postactivate"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0750"
    backup: yes
  tags:
    - deploy
    - superset

- name: Install packages required by Superset in the virtualenv.
  ansible.builtin.pip:
    virtualenv: "{{ superset_virtualenv_dir }}"
    name:
      - apache-superset
      - psycopg2-binary
      - email_validator
      - gunicorn
      - gevent
  tags:
    - deploy
    - superset

# Create config directory and files

- name: Create {{ superset_project_dir }}.
  ansible.builtin.file:
    path: "{{ superset_project_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0750"
    state: directory
  tags:
    - deploy
    - superset

- name: Create the superset_config.py file
  ansible.builtin.template:
    src: superset/superset_config.py.j2
    dest: "{{ superset_project_dir }}/superset_config.py"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0640"
    backup: yes
  tags:
    - deploy
    - superset


- name: Run Superset database migrations.
  become: yes
  become_user: "{{ app_user }}"
  environment: "{{ superset_environment }}"
  ansible.builtin.shell: "{{ superset_virtualenv_dir }}/bin/superset db upgrade"
  register: superset_migrate_result
  changed_when: "'Already up to date' not in superset_migrate_result.stdout"
  tags:
    - deploy
    - superset

- name: Create a Superset admin user
  become: yes
  become_user: "{{ app_user }}"
  ansible.builtin.shell: >-
    {{ superset_virtualenv_dir }}/bin/flask fab create-admin
    --username {{ superset_username }}
    --firstname {{ superset_firstname }}
    --lastname {{ superset_lastname }}
    --email {{ superset_email }}
    --password '{{ superset_password }}'
  environment: "{{ superset_environment }}"
  tags:
    - deploy
    - superset
    - superset-admin

- name: Run Superset initialization.
  become: yes
  become_user: "{{ app_user }}"
  environment: "{{ superset_environment }}"
  ansible.builtin.shell: "{{ superset_virtualenv_dir }}/bin/superset init && touch {{ superset_project_dir }}/.superset_init_complete"
  args:
    creates: "{{ superset_project_dir }}/.superset_init_complete"
  tags:
    - deploy
    - superset

# systemd files

- name: Create the systemd start script.
  ansible.builtin.template:
    src: superset/superset_start_script.j2
    dest: "{{ superset_virtualenv_dir }}/bin/superset_start"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0750"
    backup: yes
  tags:
    - deploy
    - superset
    - systemd

- name: Create the Superset systemd service file.
  ansible.builtin.template:
    src: systemd/superset.service.j2
    dest: /etc/systemd/system/superset.service
    owner: root
    group: root
    mode: "0644"
  tags:
    - deploy
    - superset
    - systemd

- name: Create log files.
  ansible.builtin.copy:
    content: ""
    dest: "{{ log_dir }}/{{ item }}"
    force: no
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0644"
  with_items:
    - superset.log
  tags:
    - deploy
    - superset
    - systemd

- name: Reload systemd daemon.
  ansible.builtin.systemd:
    daemon_reload: yes
  tags:
    - deploy
    - superset
    - systemd

- name: Enable and start Superset systemd service.
  ansible.builtin.systemd:
    name: superset
    state: started
    enabled: yes
  tags:
    - deploy
    - superset
    - systemd


- name: Create superset nginx config.
  ansible.builtin.template:
    src: nginx/superset_nginx_without_ssl_config.j2
    dest: /etc/nginx/sites-available/superset.conf
    backup: yes
  when: "not superset_ssl_enabled"
  tags:
    - deploy
    - superset
    - nginx

- name: Enable superset nginx config.
  ansible.builtin.file:
    src: /etc/nginx/sites-available/superset.conf
    dest: /etc/nginx/sites-enabled/superset.conf
    state: link
  when: "not superset_ssl_enabled"
  tags:
    - deploy
    - superset
    - nginx

- name: Test & reload nginx config.
  ansible.builtin.shell: nginx -t && nginx -s reload
  tags:
    - deploy
    - superset
    - nginx
