---

postgresql_version: 18
postgresql_user: postgres
postgresql_allow_remote_connections: false

default_db_name: "{{ app_name }}"
default_db_user: "{{ app_name }}"
default_db_password: "{{ vault_default_db_password }}"
default_db_host: 127.0.0.1
default_db_port: 5432

# Database backup variables
postgresql_backup_enabled: false
postgresql_backup_dir: "/var/tmp"
postgresql_backup_db_list: "superset"
postgresql_user_home_dir: "/var/lib/postgresql"
